訳修正(１．なぜXPなのか？)
xpjp/XPCoin-Whitepaper-ja pull request #20
Opened 2018-01-01 17:04 UTC by kazunari14

よろしくお願いします。

2018-01-05 13:16 UTC, MaySoMusician commented on whitepaper_ja.md
> +<u>XPを始める前に</u>、潜在的なユーザーがXPの使用例を理解することが重要です。
`before we begin`は
「まず初めに」ぐらいの意味合いかも？

2018-01-05 13:18 UTC, MaySoMusician commented on whitepaper_ja.md
> +<u>XPを始める前に</u>、潜在的なユーザーがXPの使用例を理解することが重要です。
`before we begin`は
「まず初めに」ぐらいの意味合いかも？

2018-01-05 14:19 UTC, MaySoMusician requested changes
原文とのニュアンスを変更するか否か、という視点でreviewしました
（人生初Git Review）
よろしくお願いします

2018-01-05 14:19 UTC, MaySoMusician commented on whitepaper_ja.md
> +反対に、20代半ばで素晴らしいことをしながら輝かしい栄光に包まれて人生を終えることは、「良い人生」だと考えることができます。
2行前の`充実した人生とは、無数の経験によって満たされており...`の原文は
`A life well lived is filled...`
つまり「A life well lived」＝「充実した人生」となっております（というよりこの部分は私の訳です）

そうしたら`while doing something amazing can be considered a “life well lived.”`も
`～「充実した人生」だと考えることができます。`で統一したほうが良いと思います

2018-01-05 14:19 UTC, MaySoMusician commented on whitepaper_ja.md
> +私達が人生でやること全てが経験へと変わります。
ここは改段落用の空行が必要？

2018-01-05 14:19 UTC, MaySoMusician commented on whitepaper_ja.md
> +<u>XPを始める前に</u>、潜在的なユーザーがXPの使用例を理解することが重要です。
`before we begin`は
「まず初めに」ぐらいの意味合いかも？

2018-01-05 14:19 UTC, MaySoMusician commented on whitepaper_ja.md
> +経験値を使ってみたくはないですか？経験を役立たせる方法を見つけて、自分の人生を有利に生かしたくはありませんか？
`Why not use this experience?`
この場合は「この経験を有効に活用しませんか？」とかのほうがいいかも？

2018-01-05 14:19 UTC, MaySoMusician commented on whitepaper_ja.md
>  経験を積んだ人と会って、まだ知らないユニークな体験を共有したりしてみませんか？
`...others, who also have experience,`
この関係詞のニュアンスを反映させるならば、
「あなたと同じように経験を積んでいる他の人と会って」というようになるかと

2018-01-05 14:19 UTC, MaySoMusician commented on whitepaper_ja.md
>  **経験を共有する経済を容易にするために、XPは作り出されました。**
原文と尊重するならば
`This sharing economy...`なので
`このような「経験を共有する経済」を容易にするために`

2018-01-05 14:19 UTC, MaySoMusician commented on whitepaper_ja.md
> +XPの中心的な前提条件は、それが<u>皆のため</u>であるということです。
1. `The central requirement of XP`
「XPの中心的な（前提）条件」が直訳となりますが、日本語としてわかりやすくするなら
（原文からはかけ離れますが）「XPがXPたる条件」「XPがXPであるための条件」などが考えられます
原文に則すなら「XPの重要な必要条件」「XPの根本的（必要/前提）条件」などもあり得ます
2. `that it is for everyone.`
皆のために「ある」「存在している」という意味かと思われます

2018-01-05 14:19 UTC, MaySoMusician commented on whitepaper_ja.md
>  XPはあなたの人生を向上させ、経験に基づく社会に近づけることができます。
1. `XP can enhance your life`
`あなたの人生を「充実させ」`という訳もあり得るようです
2. `bring you closer to the experience-driven community`
いい訳が思いつかない.... が、指摘点としては
「主語がyour lifeではなくyouである」「 **より** 近づける」（前者は気にしなくてもいいかもしれない）

2018-01-05 14:19 UTC, MaySoMusician commented on whitepaper_ja.md
> +XPは、あなたが為したこと、行った場所、参加したコミュニティに基づいて、経済全体の可能性を開きます。
`opens the potential`
可能性を「広げる」でもいいのだろうか？

強いて言うなら、「～コミュニティに基づく経済全体」のほうが原文に近い

2018-01-05 14:19 UTC, MaySoMusician commented on whitepaper_ja.md
>  ほとんどの暗号通貨では、使用例は単なる空想でしかありません。
`the use case is hypothetical`
他の通貨に対して若干批判的なニュアンスを込めるなら、これでも良いかと思いますが、
もし中立的な観点から述べるならば
使用例は「何かしらの仮定に基づいています」ぐらいにとどめるべきかもしれません

2018-01-05 14:19 UTC, MaySoMusician commented on whitepaper_ja.md
> +その時以来、XPは生活の多くの異なる分野で遍在してきました。ゲーミフィケーションの流行は、かつてはゲームのために用意された「経験値」という概念を、現実に利用することを可能にしました。
1. `many different areas of life`
「生活のあらゆる分野に」
2. 「ゲーミフィケーションの流行は～非常に多岐に渡ります。」を2文に分ける必要もない気がします
「ゲーミフィケーションの流行により、かつてはゲームのために用意された「経験値」という概念が、洗濯から犬の散歩に至るまでの、あらゆる日常的な仕事に対して広まりました」
... やはり少し長いですかね

2018-01-05 14:19 UTC, MaySoMusician commented on whitepaper_ja.md
> +XPは、ポイントの生成から支出先へ戻るまでのトークンの自由な移動を可能にするインセンティブ化構造の提供を活用しようとしています。
`XP seeks to capitalize on this`
「（前文にある）経験値という概念が広まったことを利用する」なので
「XPは、こうした流れを利用し、ポイントの生成から支出先へ戻るまでのトークンの自由な移動を可能にするインセンティブ化構造を提供しようとしています」というのはいかがでしょう？

2018-01-05 14:21 UTC, MaySoMusician commented on whitepaper_ja.md
> +私達が人生でやること全てが経験へと変わります。
捕捉: 37行目に空行、という意味です

2018-01-08 09:52 UTC, kazunari14 commented on whitepaper_ja.md
> +反対に、20代半ばで素晴らしいことをしながら輝かしい栄光に包まれて人生を終えることは、「良い人生」だと考えることができます。
レビューありがとうございます。「充実した人生」に統一しました。

2018-01-08 09:54 UTC, kazunari14 commented on whitepaper_ja.md
>  経験を積んだ人と会って、まだ知らないユニークな体験を共有したりしてみませんか？
修正しました。よろしくお願いします。

2018-01-08 09:59 UTC, kazunari14 commented on whitepaper_ja.md
>  XPはあなたの人生を向上させ、経験に基づく社会に近づけることができます。
反映しました。しっくりしました。ありがとうございます。

2018-01-08 10:01 UTC, kazunari14 commented on whitepaper_ja.md
> +XPは、あなたが為したこと、行った場所、参加したコミュニティに基づいて、経済全体の可能性を開きます。
なるほどです。修正しました。ありがとうございます。

2018-01-08 10:19 UTC, MaySoMusician commented on whitepaper_ja.md
> +私達が人生でやること全てが経験へと変わります。
@kazunari14 👍

2018-01-08 11:24 UTC, Naruto commented
LGTM

2018-01-08 12:14 UTC, MaySoMusician approved these changes

2018-01-08 12:16 UTC, MaySoMusician commented
皆さんご協力ありがとうございました

@kazunari14 誤字っぽいの修正しました ba1b3a5f6875818c0d69e2961843b84c6f556ee7
@Naruto review完了しました

2018-01-08 12:37 UTC, merged